server:
  port: 80
  address: '0.0.0.0'

telegram.bot:
  username: 'map_bot'
  token: 'bot_token'

spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: 'jdbc:mysql://localhost:3306/map_db'
    username: 'username'
    password: 'password'